Fix RuntimeError in aiohttp
Aiohttp expects a StreamResponse instance in its handle_request, and
will fail with a RuntimeError since aiohttp-wsgi currently returns
nothing to it:

RuntimeError: Handler <bound method _NotFoundMatchInfo._not_found of {}>
should return response instance, got <class 'NoneType'> [middlewares
(<function wsgi.<locals>.middleware_factory at 0x7f42f94d6620>,)]

This change simply returns the StreamResponse used internally to keep
aiohttp happy.

Signed-off-by: Slinky <slinky@iki.fi>